name: Hello GitHub Actions

on: [push]   # 當有人 push 時觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
